import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Challenge } from "../components/Challenge";
import Header from "../components/Header";
import { Terminal } from "../components/Terminal";
import { difficulty } from "../server/api/routers/hacker";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const [difficulty, setDifficulty] = useState<difficulty>();
  const [answer, setAnswer] = useState<string>("");
  const challenge = api.hacker.newChallenge.useQuery(
    { difficulty: difficulty as difficulty },
    { enabled: false }
  );
  const answerValid = api.hacker.submitAnswer.useQuery(
    {
      answer,
      challenge: challenge.data as string,
      difficulty: difficulty as difficulty,
    },
    { enabled: false }
  );

  return (
    <>
      <Head>
        <title>Try Crack Me</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex  h-screen flex-col items-center space-y-5 bg-gray-900 ">
        <Header />
        <div className="flex gap-5">
          {difficulty && <Terminal challenge={challenge} answer={answerValid}/>}
          <Challenge
            pickDifficulty={setDifficulty}
            newChallenge={challenge.refetch}
            challenge={challenge.data}
            updateAnswer={setAnswer}
            sendAnswer={answerValid.refetch}
          />
        </div>
      </main>
    </>
  );
};

export default Home;
