import { type NextPage } from "next";
import Head from "next/head";
import { Challenge } from "../components/challenge";
import Header from "../components/Header";
import { api } from "../utils/api";

const Home: NextPage =  () => {
  
  
  
  
  return (
    <>
      <Head>
        <title>Try Crack Me</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="bg-gray-900 h-screen flex flex-col items-center">
        <Header/>
        <Challenge/>
      </main>
    </>
  );
};

export default Home;
