import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import { api } from "../utils/api";

const Home: NextPage = () => {
  
  const message  = api.hacker.challenge.useQuery({difficulty: "medium"})
  
  return (
    <>
      <Head>
        <title>Try Crack Me</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>
        {message.data ? message.data.message : "loading ....."}
        <Header/>
      </main>
    </>
  );
};

export default Home;
